inherit: true

checks:
  php: true

build:
  image: default-bionic
  environment:
    php: 8.3.22
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]

filter:
  paths:
    - src/*
    - tests/*
